#!/bin/bash

# Copyright (c) 2011, Joshua V Dillon
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#  * Redistributions of source code must retain the above
#    copyright notice, this list of conditions and the
#    following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the
#    following disclaimer in the documentation and/or other
#    materials provided with the distribution.
#  * Neither the name of the author nor the names of its
#    contributors may be used to endorse or promote products
#    derived from this software without specific prior written
#    permission.
# 
# THIS SOFTWARE IS PROVIDED BY JOSHUA V DILLON ''AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL JOSHUA
# V DILLON BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# matlabd:
# Bash script to allow communication to a Matlab pipe.
#
# Author:
# Joshua V Dillon
#
# Revision History:
# Jan. 20. 2011  First release.

if [[ ! -p /tmp/mlpipe2 ]]; then
	mkfifo /tmp/mlpipe2;
fi

if [[ -z "$(lsof /tmp/mlpipe2)" ]]; then
	MATLAB="matlab -nosplash -r \"addpath('/var/www/html/marker')\""
	CMD="tail -f /tmp/mlpipe2 | $MATLAB 1> /tmp/matlab2.out 2>/tmp/matlab2.err &"
	echo "Starting Matlab Daemon"
	echo $CMD
	nohup bash -c "$CMD" &>/tmp/matlab.nohup
	sleep inf &
	echo "disp(datestr(now));kill($!,9);" >/tmp/mlpipe;
	wait &>/dev/null
fi

sleep $2 &
if [[ -f "$1" ]]; then
	sed -u "1d;\$a\\kill($!,9)\\;" "$1" >/tmp/mlpipe
else
	CMD="disp('`sed -e "s/'/''/g" <<<$1`');try,$1,catch ME,disp(['ERROR: ' ME.message]);end;"
	echo "$CMD,kill($!,9);" >/tmp/mlpipe
fi
wait &>/dev/null
killall -2 MATLAB
# -------------------------------------
# To "install".

#sudo ln -sf ~/repos/code/matlab/general/dillon/utility/kill/matlabd /usr/local/bin/matlabd
#sudo chmod 0555 /usr/local/bin/matlabd


# -------------------------------------
# Graveyard.

#MYPID=$$

#perl -e 'select(undef,undef,undef,.25)' #sleep for .25 sec

#trap "{
#	diff /tmp/matlab.out /tmp/matlab.old.out | \
#		sed -n 's/\(>> \)\+/>> /g;/^</s/< //p'
#	trap - 15
#	exit 0
#}" 15

#slp=1
#dur=0
#for i in {1..10..1}; do
#	sleep $slp
#	dur=$((dur+slp))
#	echo "Waiting for Matlab ($dur sec)."
#done
#echo "Giving up on Matlab ($dur sec)."

